version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: lms-postgres
    environment:
      POSTGRES_USER: lmsadmin
      POSTGRES_PASSWORD: lmspassword
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lms-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms-backend
    environment:
      DATABASE_URL: postgresql://lmsadmin:lmspassword@postgres:5432/lms_db?schema=public
      JWT_SECRET: your-secret-key-change-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - lms-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - lms-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres-data:

networks:
  lms-network:
    driver: bridge
